### ISSUE TITLE
Add Brazilian Portuguese translation for the app

### ISSUE THREAD

**Issue by rafavital** [Rostiger/Zyklus#1]
I would like to add Brazilian Portuguese to the list of languages.

**Comment by rafavital** [comment]
In the pull request #2 I have made an initial implementation of the language, though currently there is a an issue with how the "Menstruation Start" and "Menstruation End" buttons are implemented, because the app uses a combination of the "entries-start"/"entries-end" and "phase-menstruation" values of the JSON in languages.js the correct translation cannot be achieved. The button's text should be "Começo da Menstruação" and "Fim da Menstruação" for the "Menstruation Start" and "Menstruation End" equivalents.

Here are the examples:

Wrong Translation:
![Wrong "Menstruation Start" translation text](https://user-images.githubusercontent.com/29292002/119637716-54f1db00-bdec-11eb-922a-853f90a86672.png)

Correct Translation:
![Correct "Menstruation Start" translation text](https://user-images.githubusercontent.com/29292002/119637992-9bdfd080-bdec-11eb-9106-a51817064ba1.png)

My initial suggestion would be to add an entry in the languages.js for those specific buttons' texts

**Comment by Rostiger** [comment]
Hey @rafavital ! This repository moved to Source Hut and is being maintained there.
I just now saw your language contribution - thank you so much and sorry for the long delay.
I updated the code with two new entries to fix the issue you reported, please check at https://git.sr.ht/~rostiger/zyklus
Also there a whole new information section was added. If you have the time and motivation, I would love to see it translated to Portuguese as well!
Thanks and kind regards.
